'use client';
import { useState } from "react";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Header from "./Header";
import LeftSidebar from "./LeftSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function PageLayout({ children }) {
    
    const [leftSidebarOpen, setLeftSidebarOpen] = useState(true);
    
    return (
      <html lang="en">
        <body className={inter.className}>      
            <Header leftSidebarOpen={leftSidebarOpen} setLeftSidebarOpen={setLeftSidebarOpen} />
            <LeftSidebar leftSidebarOpen={leftSidebarOpen} />      
            <main className={`${leftSidebarOpen ? "ml-[260px]" : "ml-[0px]"} `}>              
                
              { children }
            </main>
        </body>
      </html>
    );
  }